install-tools:
	@echo "Installing tools..."
	@go install github.com/swaggo/swag/cmd/swag@latest
	@echo "Tools installed."

gen-swagger:
	@echo "Generating swagger..."
	@swag init
	@echo "Swagger generated."